-- colon : character is used to denote variables filled by the user or the back-end code

-- foreign keys are generated by the page
-- update should be able to set a foreign key value to NULL

-- select queries (5 - one for each table and each relationship)

-- foreign key drop down selects

-- insertion queries (5 - one for each table)

-- update queries (1 - a NULLable relationship)

-- delete queries (1 from M:N)
